config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth)
    where(uid: auth[:uid]).first_or_create do |new_user|
      new_user.uid = auth[:uid].to_s,
      new_user.nickname = auth[:info][:nickname],
      new_user.name = auth[:info][:name],
      new_user.token = auth[:credentials][:token],
      new_user.avatar_url = auth[:extra][:raw_info][:avatar_url],
      new_user.follower_count = auth[:extra][:raw_info][:followers],
      new_user.following_count = auth[:extra][:raw_info][:following]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="navmain">
        <span class="navalign">
        <span class="search">
          Search
        </span>
        <a href="github.com">Pull Issues</a>
        <a href="github.com">Market Place</a>
        <a href="github.com">Explore</a>
        <span class="navalign">
      </div>
      <div class="user">
        <% if current_user %>
          <%= current_user.name %>
          <%= link_to "Logout", logout_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign in', github_login_path %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
    <footer>
      <hr>
      <a href="github.com">© 2018 GitHub, Inc.</a>
      <a href="github.com">Terms</a>
      <a href="github.com">Privacy</a>
      <a href="github.com">Security</a>
      <a href="github.com">Status</a>
      <a href="github.com">Help</a>
      <a href="github.com">Contact GitHub</a>
      <a href="github.com">API</a>
      <a href="github.com">Training</a>
      <a href="github.com">Shop</a>
      <a href="github.com">Blog</a>
      <a href="github.com">About</a>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>